#!/bin/bash
# tools/get-device-spec.sh — Auto-generate a disk.yaml from a connected device.
#
# Usage:
#   sudo ./tools/get-device-spec.sh <device>
#
# Example:
#   sudo ./tools/get-device-spec.sh /dev/sdb
#
# Prints a disk.yaml to stdout sized to match the given block device.
# Run on the HOST before starting the container. Root privileges are required.

set -euo pipefail

die() { echo "ERROR: $*" >&2; exit 1; }

[[ $# -eq 1 ]] || die "Usage: $0 <device>  (e.g. $0 /dev/sdb)"
VOID_TARGET_DEVICE="$1"

[[ -b "${VOID_TARGET_DEVICE}" ]] || \
    die "${VOID_TARGET_DEVICE} is not a block device."

command -v lsblk    >/dev/null 2>&1 || die "lsblk is required but not found."
command -v blockdev >/dev/null 2>&1 || die "blockdev is required but not found."

VOID_DEVICE_SIZE_BYTES=$(blockdev --getsize64 "${VOID_TARGET_DEVICE}")
VOID_DEVICE_SIZE_MB=$(( VOID_DEVICE_SIZE_BYTES / 1024 / 1024 ))
VOID_DEVICE_MODEL=$(lsblk -dno MODEL "${VOID_TARGET_DEVICE}" 2>/dev/null | \
    sed 's/[[:space:]]*$//' || echo "unknown")

# Leave a 16 MiB safety margin so the image fits on any device of that size.
VOID_DISK_SIZE_MB=$(( VOID_DEVICE_SIZE_MB - 16 ))

# Swap size heuristic based on total disk size.
if   (( VOID_DISK_SIZE_MB <  32768 )); then VOID_SWAP_SIZE_MB=1024
elif (( VOID_DISK_SIZE_MB <  65536 )); then VOID_SWAP_SIZE_MB=2048
elif (( VOID_DISK_SIZE_MB < 131072 )); then VOID_SWAP_SIZE_MB=4096
else                                        VOID_SWAP_SIZE_MB=8192
fi

cat << YAML
# disk.yaml — auto-generated by tools/get-device-spec.sh
#
# Source device : ${VOID_TARGET_DEVICE}
# Device model  : ${VOID_DEVICE_MODEL}
# Device size   : ${VOID_DEVICE_SIZE_MB} MiB  (${VOID_DEVICE_SIZE_BYTES} bytes)

disk_size_mb: ${VOID_DISK_SIZE_MB}
efi_partition_size_mb: 512
boot_partition_size_mb: 512
swap_size_mb: ${VOID_SWAP_SIZE_MB}
YAML
