#!/bin/bash
# tools/get-device-spec.sh — Auto-generate a disk.yaml from a connected device.
#
# Usage:
#   ./tools/get-device-spec.sh <device>
#
# Example:
#   ./tools/get-device-spec.sh /dev/sdb
#
# The script reads the physical device's size and model, then prints a
# disk.yaml suitable for use in config/disk.yaml to stdout.  The EFI and
# boot partition sizes are kept at the recommended defaults (512 MiB each).
# The swap size is derived from a simple heuristic based on total disk size.
#
# Run this script on the HOST system (not inside the container) with the
# target storage device connected.  Root privileges are required to access
# block device attributes.

set -euo pipefail

die() { echo "ERROR: $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------
[[ $# -eq 1 ]] || die "Usage: $0 <device>  (e.g. $0 /dev/sdb)"
VOID_TARGET_DEVICE="$1"

[[ -b "${VOID_TARGET_DEVICE}" ]] || \
    die "${VOID_TARGET_DEVICE} is not a block device."

command -v lsblk  >/dev/null 2>&1 || die "lsblk is required but not found."
command -v blockdev >/dev/null 2>&1 || die "blockdev is required but not found."

# ---------------------------------------------------------------------------
# Read device attributes
# ---------------------------------------------------------------------------
VOID_DEVICE_SIZE_BYTES=$(blockdev --getsize64 "${VOID_TARGET_DEVICE}")
VOID_DEVICE_SIZE_MB=$(( VOID_DEVICE_SIZE_BYTES / 1024 / 1024 ))
VOID_DEVICE_MODEL=$(lsblk -dno MODEL "${VOID_TARGET_DEVICE}" 2>/dev/null | \
    sed 's/[[:space:]]*$//' || echo "unknown")

# Leave a small safety margin (16 MiB) below the physical size so that the
# image fits on any device of that nominal size.
VOID_DISK_SIZE_MB=$(( VOID_DEVICE_SIZE_MB - 16 ))

# ---------------------------------------------------------------------------
# Heuristic: choose swap size based on disk size.
#   < 32 GiB  →  1024 MiB swap
#   < 64 GiB  →  2048 MiB swap
#   < 128 GiB →  4096 MiB swap
#   >= 128 GiB → 8192 MiB swap
# ---------------------------------------------------------------------------
if   (( VOID_DISK_SIZE_MB < 32768 ));  then VOID_SWAP_SIZE_MB=1024
elif (( VOID_DISK_SIZE_MB < 65536 ));  then VOID_SWAP_SIZE_MB=2048
elif (( VOID_DISK_SIZE_MB < 131072 )); then VOID_SWAP_SIZE_MB=4096
else                                        VOID_SWAP_SIZE_MB=8192
fi

# ---------------------------------------------------------------------------
# Emit disk.yaml
# ---------------------------------------------------------------------------
cat << YAML
# disk.yaml — auto-generated by tools/get-device-spec.sh
#
# Source device : ${VOID_TARGET_DEVICE}
# Device model  : ${VOID_DEVICE_MODEL}
# Device size   : ${VOID_DEVICE_SIZE_MB} MiB  (${VOID_DEVICE_SIZE_BYTES} bytes)
#
# All sizes are in mebibytes (MiB).

disk_size_mb: ${VOID_DISK_SIZE_MB}
efi_partition_size_mb: 512
boot_partition_size_mb: 512
swap_size_mb: ${VOID_SWAP_SIZE_MB}
YAML
